# Generated by Django 4.2.2 on 2023-07-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_pet_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='pet_allowed',
        ),
        migrations.AddField(
            model_name='house',
            name='pets_allowed',
            field=models.BooleanField(default=True, help_text='Does this house allow pets?', verbose_name='Pets Allowed?'),
        ),
    ]
